spring:
  application:
    name: windfinder-alert
  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/alert
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  store-type: jdbc
  mail:
    host:
      ${MAIL_SMTP}
    port:
      ${MAIL_PORT}
    username:
      ${MAIL_USERNAME}
    password:
      ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable:
              true


server:
  port:
    8080
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000